### ISSUE TITLE
Chrome extension not working in "New" Reddit

### ISSUE THREAD

**Issue by dexygen** [gcp/rchesspgn#1]
Please visit https://www.reddit.com/r/chessgotw/comments/8merwh/beautiful_sacrificial_miniature_sicilian_as_black/ in both old Reddit and new Reddit.  It works fine in old Reddit but not in new:

![Reddit PGN Viewer not working](https://i.imgur.com/EJOOZl5.png)

I have read the code and think I have the solution.  Posts are now classed appropriately with `Post` and likewise comments with `Comment`.  So it may just be a matter of updating line 4 of rchesspgn as follows:
```
$(obj).find('.usertext-body, .faukuq-10, .Post, .Comment').each(function () {
```
However I'm not sure what .faukuq-10 is supposed to do and actually didn't find it in the DOM, so I'm not making a pull request at this time, and rather merely just logging this issue.  Thanks in advance for your attention.

**Comment by gcp** [comment]
.Post and .Comment sure seem like nicer markers than the "faukuq" that was there before. It seems to work, ~~although the exact one you linked to will generate an error that the game can't be parsed correctly.~~

**Comment by gcp** [comment]
Updated version pushed to AMO: https://addons.mozilla.org/en-US/firefox/addon/reddit-pgn-viewer/

I notice that your topic was talking about "Chrome", but I don't use Chrome and the Chrome extension wasn't published by me. The source of this one should work almost unmodified in Chrome though, if someone wants to try.

**Comment by dexygen** [comment]
OK thanks I'll try to find out who maintains the Chrome plugin and if I can't I might have to create a slightly altered one based on your work, properly referencing/adhering-to the license, etc.  Thanks.
